# Generated by Django 4.2.3 on 2023-09-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=10)),
            ],
        ),
    ]
