# Generated by Django 4.2.3 on 2023-09-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttable',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
