# Generated by Django 4.2.3 on 2023-09-25 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_posttable_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttable',
            name='id',
        ),
        migrations.AddField(
            model_name='posttable',
            name='post_id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
