# Generated by Django 4.2.3 on 2023-09-25 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_posttable_category_remove_posttable_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttable',
            name='post_id',
        ),
        migrations.AddField(
            model_name='posttable',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
