# Generated by Django 4.2.3 on 2023-09-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='id_card',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
