# Generated by Django 4.2.3 on 2023-09-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_studenttable_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfotable',
            name='medical_sheet',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
