# Generated by Django 4.2.3 on 2023-09-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_medicalinfotable_medical_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images/'),
        ),
    ]
