# Generated by Django 4.2.3 on 2023-09-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
            ],
        ),
    ]
