# Generated by Django 4.2.3 on 2023-09-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
